name: CI Backend
on:{push:{branches:["main"]},pull_request:{branches:["main"]}}
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:{node-version:"lts/*"}
    - run: cd backend && npm install
    - run: cd backend && npm test