name: Deploy (Simulado)
on:
  workflow_run:
    workflows:["CI Backend","CI Frontend"]
    types:[completed]
jobs:
  deploy:
    if:${{ github.event.workflow_run.conclusion=='success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:{node-version:"lts/*"}
    - run: cd backend && npm install && echo "build backend"
    - run: cd frontend && npm install && npm run build
    - run: mkdir deploy && cp -r backend deploy/backend && cp -r frontend/dist deploy/frontend
    - run: echo "Despliegue completado" 